# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║         KUBERNETES LOADBALANCER SERVICE - COMPLETE LEARNING GUIDE         ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
#
# This file demonstrates:
# 1. A Deployment that creates 3 replicas of a FastAPI backend
# 2. A LoadBalancer Service that exposes those pods via an external IP
#
# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                          TABLE OF CONTENTS                                  │
# ├─────────────────────────────────────────────────────────────────────────────┤
# │  1. Service Type Comparison                                                 │
# │  2. Architecture Flow Diagram                                               │
# │  3. LoadBalancer vs NodePort                                                │
# │  4. Minikube LoadBalancer Setup                                             │
# │  5. Deployment Manifest                                                     │
# │  6. Service Manifest                                                        │
# │  7. Useful kubectl Commands                                                 │
# └─────────────────────────────────────────────────────────────────────────────┘
#
#
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                      1. SERVICE TYPE COMPARISON                           ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
#
#   ┌────────────────────┬──────────────────────────────────────────────────────┐
#   │   Service Type     │   Description                                        │
#   ├────────────────────┼──────────────────────────────────────────────────────┤
#   │   ClusterIP        │ • Default service type                               │
#   │                    │ • Internal-only access (within cluster)              │
#   │                    │ • Gets a virtual IP from cluster IP range            │
#   │                    │ • Use for: backend services, databases               │
#   ├────────────────────┼──────────────────────────────────────────────────────┤
#   │   NodePort         │ • Extends ClusterIP                                  │
#   │                    │ • Exposes service on EACH Node's IP                  │
#   │                    │ • Opens static port (30000-32767) on all nodes       │
#   │                    │ • Use for: dev/test, simple external access          │
#   ├────────────────────┼──────────────────────────────────────────────────────┤
#   │   LoadBalancer     │ • Extends NodePort                                   │
#   │   (THIS FILE)      │ • Provisions cloud load balancer (AWS/GCP/Azure)     │
#   │                    │ • Provides single external IP address                │
#   │                    │ • Use for: production external access                │
#   └────────────────────┴──────────────────────────────────────────────────────┘
#
#
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                      2. ARCHITECTURE FLOW DIAGRAM                         ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
#
#   EXTERNAL WORLD (Internet/Browser/Client)
#           │
#           │ HTTP Request to LoadBalancer External IP
#           │ Example: curl http://192.168.49.2
#           ▼
#   ┌───────────────────────────────────────────────────────────────────────┐
#   │                      CLOUD LOAD BALANCER                              │
#   │              (or Minikube Tunnel for local dev)                       │
#   │                   External IP: 192.168.49.2                           │
#   └──────────────────────────────┬────────────────────────────────────────┘
#           │
#           │ Forwards to NodePort
#           ▼
#   ┌───────────────────────────────────────────────────────────────────────┐
#   │                         KUBERNETES CLUSTER                            │
#   │                                                                       │
#   │  ┌─────────────────────────────────────────────────────────────────┐  │
#   │  │                    NODE 1 (Worker Machine)                      │  │
#   │  │                                                                 │  │
#   │  │   ┌─────────────────────────────────────────────────────────┐   │  │
#   │  │   │            SERVICE: fastapi-lb-service                  │   │  │
#   │  │   │            ──────────────────────────                   │   │  │
#   │  │   │            Type: LoadBalancer                           │   │  │
#   │  │   │            ClusterIP: 10.96.x.x (auto-assigned)         │   │  │
#   │  │   │            External IP: 192.168.49.2 (via LB)           │   │  │
#   │  │   │            Port: 80                                     │   │  │
#   │  │   │            Selector: app=fastapi                        │   │  │
#   │  │   └──────────────────────────┬──────────────────────────────┘   │  │
#   │  │                              │                                  │  │
#   │  │          ┌───────────────────┼───────────────────┐              │  │
#   │  │          │  kube-proxy       │ (load balancing)  │              │  │
#   │  │          │                   │                   │              │  │
#   │  │          ▼                   ▼                   ▼              │  │
#   │  │   ┌───────────┐       ┌───────────┐       ┌───────────┐         │  │
#   │  │   │   POD 1   │       │   POD 2   │       │   POD 3   │         │  │
#   │  │   │ ───────── │       │ ───────── │       │ ───────── │         │  │
#   │  │   │ app=      │       │ app=      │       │ app=      │         │  │
#   │  │   │ fastapi   │       │ fastapi   │       │ fastapi   │         │  │
#   │  │   │           │       │           │       │           │         │  │
#   │  │   │ ┌───────┐ │       │ ┌───────┐ │       │ ┌───────┐ │         │  │
#   │  │   │ │fastapi│ │       │ │fastapi│ │       │ │fastapi│ │         │  │
#   │  │   │ │ :80   │ │       │ │ :80   │ │       │ │ :80   │ │         │  │
#   │  │   │ └───────┘ │       │ └───────┘ │       │ └───────┘ │         │  │
#   │  │   │           │       │           │       │           │         │  │
#   │  │   │ IP:       │       │ IP:       │       │ IP:       │         │  │
#   │  │   │ 10.244.x.1│       │ 10.244.x.2│       │ 10.244.x.3│         │  │
#   │  │   └───────────┘       └───────────┘       └───────────┘         │  │
#   │  │                                                                 │  │
#   │  └─────────────────────────────────────────────────────────────────┘  │
#   │                                                                       │
#   └───────────────────────────────────────────────────────────────────────┘
#
#
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                    3. LOADBALANCER VS NODEPORT                            ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
#
#   ┌──────────────────┬─────────────────────┬─────────────────────────────┐
#   │    Feature       │      NodePort       │       LoadBalancer          │
#   ├──────────────────┼─────────────────────┼─────────────────────────────┤
#   │ External Access  │ <NodeIP>:<NodePort> │ Single External IP          │
#   │                  │ Multiple endpoints  │ One clean endpoint          │
#   ├──────────────────┼─────────────────────┼─────────────────────────────┤
#   │ Port Range       │ 30000-32767         │ Standard ports (80, 443)    │
#   ├──────────────────┼─────────────────────┼─────────────────────────────┤
#   │ Load Balancing   │ Manual (DNS/proxy)  │ Automatic (cloud LB)        │
#   ├──────────────────┼─────────────────────┼─────────────────────────────┤
#   │ Cloud Cost       │ Free                │ Costs per LB                │
#   ├──────────────────┼─────────────────────┼─────────────────────────────┤
#   │ Production Use   │ Not recommended     │ Recommended                 │
#   ├──────────────────┼─────────────────────┼─────────────────────────────┤
#   │ SSL Termination  │ Manual setup        │ Often built-in              │
#   └──────────────────┴─────────────────────┴─────────────────────────────┘
#
#
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                   4. MINIKUBE LOADBALANCER SETUP                          ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
#
#   Minikube doesn't have a real cloud load balancer, so you need to:
#
#   1. Apply this manifest:
#      kubectl apply -f service-loadbalancer.yaml
#
#   2. In a SEPARATE TERMINAL, run minikube tunnel:
#      minikube tunnel
#      (This creates a network route and assigns an External IP)
#      (Keep this terminal running!)
#
#   3. Check the External IP:
#      kubectl get service fastapi-lb-service
#
#   4. Access your service:
#      curl http://<EXTERNAL-IP>
#
#   ⚠️  IMPORTANT: minikube tunnel must stay running, or External IP becomes <pending>
#
#
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                         5. DEPLOYMENT MANIFEST                            ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
#
# For detailed Deployment documentation, see: deployment.yaml
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi_app:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "256m"
            limits:
              memory: "128Mi"
              cpu: "512m"

---
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                          6. SERVICE MANIFEST                              ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
#
# LoadBalancer Service - Provisions external load balancer
#
# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                         SESSION AFFINITY EXPLAINED                          │
# ├─────────────────────────────────────────────────────────────────────────────┤
# │                                                                             │
# │  sessionAffinity controls how requests are distributed across pods:        │
# │                                                                             │
# │  ┌──────────────┬──────────────────────────────────────────────────────┐   │
# │  │   Option     │   Behavior                                           │   │
# │  ├──────────────┼──────────────────────────────────────────────────────┤   │
# │  │   None       │ • Round-robin load balancing                         │   │
# │  │  (Default)   │ • Each request can go to any pod                     │   │
# │  │              │ • Best for stateless applications                    │   │
# │  │              │ • Maximizes load distribution                        │   │
# │  ├──────────────┼──────────────────────────────────────────────────────┤   │
# │  │   ClientIP   │ • Sticky sessions based on client IP                 │   │
# │  │              │ • Same client always goes to same pod                │   │
# │  │              │ • Useful for stateful apps (sessions, caches)        │   │
# │  │              │ • Can cause uneven load distribution                 │   │
# │  └──────────────┴──────────────────────────────────────────────────────┘   │
# │                                                                             │
# │  WHEN TO USE ClientIP:                                                      │
# │    ✓ User sessions stored in pod memory (not recommended pattern)          │
# │    ✓ WebSocket connections that need consistency                           │
# │    ✓ Shopping carts stored locally in pods                                 │
# │    ✓ File upload sessions that span multiple requests                      │
# │                                                                             │
# │  WHEN TO USE None:                                                          │
# │    ✓ Stateless REST APIs (recommended)                                     │
# │    ✓ Microservices with external state (databases, Redis)                  │
# │    ✓ Better load distribution across pods                                  │
# │    ✓ Easier horizontal scaling                                             │
# │                                                                             │
# │  EXAMPLE SCENARIOS:                                                         │
# │                                                                             │
# │    sessionAffinity: None                                                    │
# │    ────────────────────────                                                 │
# │    Request 1 from 192.168.1.100 → Pod A                                    │
# │    Request 2 from 192.168.1.100 → Pod B  (different pod!)                  │
# │    Request 3 from 192.168.1.100 → Pod C  (different pod!)                  │
# │                                                                             │
# │    sessionAffinity: ClientIP                                                │
# │    ────────────────────────────                                             │
# │    Request 1 from 192.168.1.100 → Pod A                                    │
# │    Request 2 from 192.168.1.100 → Pod A  (same pod!)                       │
# │    Request 3 from 192.168.1.100 → Pod A  (same pod!)                       │
# │                                                                             │
# │  TESTING LOAD BALANCING:                                                    │
# │    # With sessionAffinity: None, you'll see requests distributed           │
# │    for i in {1..20}; do curl http://localhost:8080; done                   │
# │                                                                             │
# │    # Check which pods received requests:                                   │
# │    kubectl logs -l app=fastapi --tail=20 --prefix                          │
# │                                                                             │
# └─────────────────────────────────────────────────────────────────────────────┘
#
apiVersion: v1
kind: Service
metadata:
  name: fastapi-lb-service
spec:
  type: LoadBalancer

  # sessionAffinity: None enables round-robin load balancing
  # This means each request can go to any available pod
  # Best for stateless applications like REST APIs
  sessionAffinity: None

  # Alternative: sessionAffinity: ClientIP
  # Uncomment below to enable sticky sessions (same client → same pod)
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800  # Session timeout (default: 3 hours)

  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                       7. USEFUL KUBECTL COMMANDS                          ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
#
# DEPLOYMENT:
#   kubectl apply -f service-loadbalancer.yaml
#   kubectl delete -f service-loadbalancer.yaml
#
# VERIFICATION:
#   kubectl get deployments
#   kubectl get pods -l app=fastapi
#   kubectl get services
#   kubectl describe service fastapi-lb-service
#
# GET EXTERNAL IP (wait for it to be assigned):
#   kubectl get service fastapi-lb-service
#   # Look for EXTERNAL-IP column (not <pending>)
#
# ACCESS (Minikube - requires minikube tunnel in separate terminal):
#   minikube tunnel    # Run in separate terminal, keep running
#   kubectl get service fastapi-lb-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
#   curl http://<EXTERNAL-IP>
#
# ACCESS (Cloud - AWS/GCP/Azure):
#   kubectl get service fastapi-lb-service
#   # External IP is automatically provisioned by cloud provider
#   curl http://<EXTERNAL-IP>
#
# DEBUGGING:
#   kubectl logs -l app=fastapi
#   kubectl exec -it <pod-name> -- /bin/sh
#   kubectl get endpoints fastapi-lb-service
#
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                           RELATED FILES                                   ║
# ╠═══════════════════════════════════════════════════════════════════════════╣
# ║  • deployment.yaml       - Detailed Deployment documentation              ║
# ║  • service-clusterip.yaml - ClusterIP Service (internal only)             ║
# ║  • service-nodeport.yaml  - NodePort Service (external via node ports)    ║
# ║  • replicaset.yaml       - ReplicaSet documentation                       ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
